# Generated by Django 6.0.1 on 2026-02-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='adresse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='statut',
            field=models.CharField(choices=[('stable', 'Stable'), ('suivi', 'Sous suivi'), ('critique', 'Critique')], default='stable', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='telephone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
