"""
Django settings for mentcare_backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# -------------------- Base --------------------
BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'ton-secret-key-ici'

DEBUG = True

ALLOWED_HOSTS = []

# -------------------- Applications --------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',

    # Local apps
    'patients',
    'consultations',
    'users',
    'reports',
]

# -------------------- Middleware --------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # IMPORTANT pour Angular
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# -------------------- URLs --------------------
ROOT_URLCONF = 'mentcare_backend.urls'

# -------------------- WSGI --------------------
WSGI_APPLICATION = 'mentcare_backend.wsgi.application'

# -------------------- Templates --------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# -------------------- Base de données --------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mentcare',
        'USER': 'mentcare_user',
        'PASSWORD': 'MentcarePass123',
        'HOST': 'localhost',
        'PORT': '3306',
    }
}

# -------------------- Validators --------------------
AUTH_PASSWORD_VALIDATORS = []

# -------------------- Localisation --------------------
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Douala'
USE_I18N = True
USE_TZ = True

# -------------------- Static --------------------
STATIC_URL = '/static/'

# -------------------- Custom User --------------------
AUTH_USER_MODEL = 'users.User'

# -------------------- Django REST Framework --------------------
REST_FRAMEWORK = {

    # JWT Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

    # Permissions globales
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),

    # Pagination (important Angular tables)
    'DEFAULT_PAGINATION_CLASS':
        'rest_framework.pagination.PageNumberPagination',

    'PAGE_SIZE': 10,
}

# -------------------- CORS --------------------
CORS_ALLOW_ALL_ORIGINS = True
# Pour production plus tard :
# CORS_ALLOWED_ORIGINS = ["http://localhost:4200"]
from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
]

from datetime import timedelta

SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer',),
}
